name: nico-vit-xai
channels: [pytorch, nvidia, conda-forge]
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - pyyaml
  - matplotlib
  - pillow
  - tqdm
  - seaborn
  - pip
  - pip:
      - timm>=0.9.16
      - opencv-python
      - clip-anytorch
